name: ticket_app
description: A new Flutter project.

# Add this environment section
environment:
  sdk: '>=3.0.0 <4.0.0' # This is a common and robust constraint for Flutter 3.x

# The following line ensures that the Material Icons font is
# included with your application, so that you can use the icons in
# the Material Icons class.
uses-material-design: true

# ... (rest of your pubspec.yaml content) ...

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0